In [1]:
import numpy as np

In [42]:
help(np.meshgrid)

Help on function meshgrid in module numpy:

meshgrid(*xi, **kwargs)
    Return coordinate matrices from coordinate vectors.
    
    Make N-D coordinate arrays for vectorized evaluations of
    N-D scalar/vector fields over N-D grids, given
    one-dimensional coordinate arrays x1, x2,..., xn.
    
    .. versionchanged:: 1.9
       1-D and 0-D cases are allowed.
    
    Parameters
    ----------
    x1, x2,..., xn : array_like
        1-D arrays representing the coordinates of a grid.
    indexing : {'xy', 'ij'}, optional
        Cartesian ('xy', default) or matrix ('ij') indexing of output.
        See Notes for more details.
    
        .. versionadded:: 1.7.0
    sparse : bool, optional
        If True a sparse grid is returned in order to conserve memory.
        Default is False.
    
        .. versionadded:: 1.7.0
    copy : bool, optional
        If False, a view into the original arrays are returned in order to
        conserve memory.  Default is True.  Please note that
  

In [47]:
grid = np.vstack(
    np.dstack(
        np.meshgrid(
            np.linspace(0., 1., 4),
            np.linspace(1., 0., 4)
            )
        )
    )

In [48]:
grid

array([[[0.        , 1.        ],
        [0.33333333, 1.        ],
        [0.66666667, 1.        ],
        [1.        , 1.        ]],

       [[0.        , 0.66666667],
        [0.33333333, 0.66666667],
        [0.66666667, 0.66666667],
        [1.        , 0.66666667]],

       [[0.        , 0.33333333],
        [0.33333333, 0.33333333],
        [0.66666667, 0.33333333],
        [1.        , 0.33333333]],

       [[0.        , 0.        ],
        [0.33333333, 0.        ],
        [0.66666667, 0.        ],
        [1.        , 0.        ]]])

In [50]:
np.vstack(grid)

array([[0.        , 1.        ],
       [0.33333333, 1.        ],
       [0.66666667, 1.        ],
       [1.        , 1.        ],
       [0.        , 0.66666667],
       [0.33333333, 0.66666667],
       [0.66666667, 0.66666667],
       [1.        , 0.66666667],
       [0.        , 0.33333333],
       [0.33333333, 0.33333333],
       [0.66666667, 0.33333333],
       [1.        , 0.33333333],
       [0.        , 0.        ],
       [0.33333333, 0.        ],
       [0.66666667, 0.        ],
       [1.        , 0.        ]])

In [30]:
grid.reshape((16, 16, 2))

array([[[0.        , 1.        ],
        [0.00392157, 0.99607843],
        [0.00784314, 0.99215686],
        [0.01176471, 0.98823529],
        [0.01568627, 0.98431373],
        [0.01960784, 0.98039216],
        [0.02352941, 0.97647059],
        [0.02745098, 0.97254902],
        [0.03137255, 0.96862745],
        [0.03529412, 0.96470588],
        [0.03921569, 0.96078431],
        [0.04313725, 0.95686275],
        [0.04705882, 0.95294118],
        [0.05098039, 0.94901961],
        [0.05490196, 0.94509804],
        [0.05882353, 0.94117647]],

       [[0.0627451 , 0.9372549 ],
        [0.06666667, 0.93333333],
        [0.07058824, 0.92941176],
        [0.0745098 , 0.9254902 ],
        [0.07843137, 0.92156863],
        [0.08235294, 0.91764706],
        [0.08627451, 0.91372549],
        [0.09019608, 0.90980392],
        [0.09411765, 0.90588235],
        [0.09803922, 0.90196078],
        [0.10196078, 0.89803922],
        [0.10588235, 0.89411765],
        [0.10980392, 0.89019608],
        [0.1

In [14]:
len(grid)

256

In [17]:
256 ** 2

65536

In [18]:
16 ** 2

256