In [1]:
import sys
import os
workPath = os.path.abspath('..')
if not workPath in sys.path:
    sys.path.append(workPath)

In [2]:
from planetengine.systems import isovisc

In [3]:
system = isovisc.build()

In [5]:
myouts = system.out()

In [10]:
step, time, temp, tempDot = myouts

In [16]:
import numpy as np

In [15]:
temp

array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])

In [17]:
system.store()

In [18]:
system.stored

[(array(0, dtype=int32), array(0.0), array([[ 0.],
         [ 0.],
         [ 0.],
         ..., 
         [ 0.],
         [ 0.],
         [ 0.]]), array([[ 1.        ],
         [ 0.97456147],
         [ 0.94914657],
         ..., 
         [ 0.05085343],
         [ 0.02543853],
         [ 0.        ]]))]

In [19]:
system.iterate()

In [20]:
system.store()

In [21]:
system.stored

[(array(0, dtype=int32), array(0.0), array([[ 0.],
         [ 0.],
         [ 0.],
         ..., 
         [ 0.],
         [ 0.],
         [ 0.]]), array([[ 1.        ],
         [ 0.97456147],
         [ 0.94914657],
         ..., 
         [ 0.05085343],
         [ 0.02543853],
         [ 0.        ]])),
 (array(1, dtype=int32), array(7.900428632971577e-08), array([[    0.        ],
         [-5084.68952359],
         [-9906.31507657],
         ..., 
         [ 7000.13349608],
         [ 3288.74809584],
         [    0.        ]]), array([[ 1.        ],
         [ 0.97436061],
         [ 0.94875525],
         ..., 
         [ 0.05112995],
         [ 0.02556845],
         [ 0.        ]]))]

In [22]:
processed = list(map(np.stack, (list(map(list, zip(*system.stored))))))

In [23]:
processed

[array([0, 1], dtype=int32),
 array([  0.00000000e+00,   7.90042863e-08]),
 array([[[    0.        ],
         [    0.        ],
         [    0.        ],
         ..., 
         [    0.        ],
         [    0.        ],
         [    0.        ]],
 
        [[    0.        ],
         [-5084.68952359],
         [-9906.31507657],
         ..., 
         [ 7000.13349608],
         [ 3288.74809584],
         [    0.        ]]]),
 array([[[ 1.        ],
         [ 0.97456147],
         [ 0.94914657],
         ..., 
         [ 0.05085343],
         [ 0.02543853],
         [ 0.        ]],
 
        [[ 1.        ],
         [ 0.97436061],
         [ 0.94875525],
         ..., 
         [ 0.05112995],
         [ 0.02556845],
         [ 0.        ]]])]

In [ ]:
list(system.out())

In [ ]:
system.stored

In [ ]:
system.store()

In [ ]:
system.iterate()

In [ ]:
system.store()